### PR TITLE
Fixes autolinking for double colon operator

### LINKED ISSUE #130: `autolink_url()` doesn't work as expected with the double colon operator
While working on #129, I was testing a few things and, if I am not mistaken, `autolink_url()` doesn't work as expected with infix operators.

``` r
library(downlit)

# regular
autolink_url("base::mean()")
#> [1] "https://rdrr.io/r/base/mean.html"

# prefix
autolink_url("base::`if`()")
#> [1] "https://rdrr.io/r/base/Control.html"

# infix 
autolink_url("base::`::`()")
#> Error in expr[[2]]: subscript out of bounds
```

<sup>Created on 2022-03-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I also made sure that this is a valid syntax for using namespace operator with infix operators:

``` r
base::`::`("base", "log")
#> function (x, base = exp(1))  .Primitive("log")
```

<sup>Created on 2022-03-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
``base::`::`()`` tripped `href_expr()` because the function name is provided with `::` *and* no. of arguments is 0. 
This led the control flow in the wrong part of the conditionals. Reordering them does the trick!

# before

``` r
downlit::autolink_url("base::`::`()")
#> Error in expr[[2]]: subscript out of bounds
```

# after

``` r
downlit::autolink_url("base::`::`()")
#> [1] "https://rdrr.io/r/base/ns-dblcolon.html"
```

<sup>Created on 2022-03-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Closes #130

### CODE REVIEW

**Review by dmurdoch — COMMENTED** [review]
You might think about moving that `n_args == 0` case two blocks higher, so that cases like `utils::help()` links to the `help` page, and `?` with no arg gets a link to Question.

**Comment by dmurdoch** [comment]
One other comment:  

    autolink_url("`::`(utils)")

still gives the subscript out of bounds error.  Maybe test `n_args >= 2` in the `::` special casing, and leave the blocks in the same order?

**Comment by IndrajeetPatil** [comment]
> still gives the subscript out of bounds error

But `` `::`(utils) `` is not a valid function call, no?

``` r
library(downlit)

autolink_url("`::`(utils)")
#> Error in expr[[3]]: subscript out of bounds

`::`(utils)
#> Error in `::`(utils): 1 argument passed to '::' which requires 2
```

I don't see this issue with a valid function call.

```r
autolink_url('base::`::`("utils", "adist")')
#> [1] "https://rdrr.io/r/utils/adist.html"

autolink_url('`::`("utils", "adist")')
#> [1] "https://rdrr.io/r/utils/adist.html"
```

<sup>Created on 2022-03-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>


Am I missing something?

**Comment by dmurdoch** [comment]
It's a very similar error with 

     base::`::`()

which was the motivating example for the PR:

    Error in base::`::`() : 0 arguments passed to '::' which requires 2

**Comment by IndrajeetPatil** [comment]
@dmurdoch Thanks for the suggestion! This works now.

``` r
library(downlit)

autolink_url("utils::help()") 
#> [1] "https://rdrr.io/r/utils/help.html"
```

<sup>Created on 2022-03-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
> Maybe test n_args >= 2 in the :: special casing, and leave the blocks in the same order?

Hmm, let me have a look.

File: R/link.R [hunk 1]
```diff
@@ -111,6 +111,8 @@ href_expr <- function(expr) {
       # package?x
       href_topic(paste0(expr[[3]], "-", expr[[2]]))
     }
+  } else if (n_args == 0) {
```
Comment (hadley) [inline R/link.R:114]: I think it would be cleaner if each block checked both the function name and the expected number of arguments.

File: tests/testthat/test-link.R [hunk 2]
```diff
@@ -67,6 +67,21 @@ test_that("can link to functions in base packages", {
   expect_equal(href_expr_(median()), href_topic_remote("median", "stats"))
 })
 
+test_that("can link to namespaced infix operators in base packages", {
```
Comment (hadley) [inline tests/testthat/test-link.R:70]: I don't see how the tests relate to the change that you've made above. I would expect to see roughly one test for each of the blocks in the if statement. Can you please focus in on the key changes?

**Comment by hadley** [comment]
@IndrajeetPatil in the future, can you please use an informative title for the pull request? The `Closes #130` should go in the description, not the title.

**Comment by hadley** [comment]
Thanks!
